// <auto-generated />
using System;
using EnglishBattle.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnglishBattle.DAL.Migrations
{
    [DbContext(typeof(EnglishBattleContext))]
    [Migration("20231010231712_AddVerbTranslation")]
    partial class AddVerbTranslation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("EnglishBattle.DAL.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("OverAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Seconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.GameAnswer", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VerbId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PastParticipleInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastSimpleInput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimePenalty")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "VerbId");

                    b.HasIndex("VerbId");

                    b.ToTable("GameAnswers");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.IrregularVerb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseForm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastParticiple")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PastSimple")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("IrregularVerbs");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.Game", b =>
                {
                    b.HasOne("EnglishBattle.DAL.Entities.Player", "Player")
                        .WithMany("Games")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.GameAnswer", b =>
                {
                    b.HasOne("EnglishBattle.DAL.Entities.Game", "Game")
                        .WithMany("Answers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnglishBattle.DAL.Entities.IrregularVerb", "Verb")
                        .WithMany()
                        .HasForeignKey("VerbId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Verb");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.Game", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("EnglishBattle.DAL.Entities.Player", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
